# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-18 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20170217_1034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
